### PR TITLE
Added input form to client

### PR DESCRIPTION
**Pull request by kcavicchio**
Add dropdown inputs for person, place, weapon, as well as button to Make an Accusation

### CODE REVIEW

**Review by EthanChe — DISMISSED** [review]
lgtm!

**Review by EthanChe — CHANGES_REQUESTED** [review]
When running multiple clients, the "make accusation" components on the bottom only show up for the person that clicked "start game". The other clients should add these HTML components when they receive the drawboard message.

**Review by zlmcdaniel — DISMISSED** [review]
Looks good!

**Review by EthanChe — APPROVED** [review]
lgtm

**Review by tatahseen — APPROVED** [review]

**Pull request merged**
